### ISSUE TITLE
Node 18: Error: spawn nj-cli ENOENT

### ISSUE THREAD

**Issue by Powersource** [ssbc/ssb-db2#391] opened 2022-09-21 13:48 UTC
```
% npm i
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/me/prj/ssb/ssb-db2/node_modules/ssb-validate2-rsjs-node
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! node:internal/errors:484
npm ERR!     ErrorCaptureStackTrace(err);
npm ERR!     ^
npm ERR! 
npm ERR! Error: spawn nj-cli ENOENT
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
npm ERR!     at onErrorNT (node:internal/child_process:476:16)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawn nj-cli',
npm ERR!   path: 'nj-cli',
npm ERR!   spawnargs: [ 'build', '--release' ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.9.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/me/.npm/_logs/2022-09-21T13_27_51_762Z-debug-0.log
```

**Comment by Powersource** [comment] 2022-09-21 13:49
Works on node 16 for me

**Comment by staltz** [comment] 2022-09-21 16:54
I can't reproduce it. One suspicion: try deleting package-lock.json, if you have it. Because I don't see any reason why there would be ssb-validate2-rsjs-node in our dependencies anymore.

**Comment by Powersource** [comment] 2022-09-21 20:44
I think this was right after i had cloned it

**Comment by staltz** [comment] 2022-10-12 08:17
Closing, unless we find a way to reproduce

**Closed by staltz** 2022-10-12 08:17 UTC
